# -*- coding: utf-8 -*-
"""ProdigyTask_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XdeAzww2qHtRiWB1jsCEhCTY4O-sPOi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

df = pd.read_csv("/content/worldpopulationdata.csv")

df.head()

df.tail(5)

df.columns

df.info()

df.describe()

df.duplicated().sum()

df.isnull().sum()

print(df['Country Name'].unique())
print("\n Total no of unique countries:",df['Country Name'].nunique())

print(df['Country Code'].unique())
print("\n Total no of unique country code:",df['Country Code'].nunique())

df.drop(['Series Name','Country Name'],axis=1,inplace=True)

# Filter data for total population
total_population_data = df[df['Series Code'] == 'SP.POP.TOTL']

# Sort data based on the total population for 2022
total_population_sorted = total_population_data.sort_values(by="2022", ascending=False)

# Get the top ten countries with the highest total population for 2022
total_top_ten_countries = total_population_sorted.head(10)
print("Top ten countries of total population\n")
print(total_top_ten_countries[['Country Code']])

import matplotlib.pyplot as plt
import seaborn as sns
# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,1)
sns.barplot(x="2022", y="Country Code", data=total_top_ten_countries, palette="coolwarm")
plt.title("Top Ten Countries of Total Population (2022)",fontsize=10)
plt.xlabel("Total Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,2)
sns.barplot(x="2016", y="Country Code", data=total_top_ten_countries, palette="coolwarm")
plt.title("Top Ten Countries of Total Population (2016)",fontsize=10)
plt.xlabel("Total Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

# Sort data based on the total population for 2022
total_population_sorted1 = total_population_data.sort_values(by="2022", ascending=True)

# Get the top ten countries with the highest total population for 2022
total_bottom_ten_countries = total_population_sorted1.head(10)
print("Bottom ten countries of total population\n")
print(total_bottom_ten_countries[['Country Code']])

# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,1)
sns.barplot(x="2022", y="Country Code", data=total_bottom_ten_countries, palette="coolwarm")
plt.title("Bottom Ten Countries of Total Population (2022)",fontsize=10)
plt.xlabel("Total Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,2)
sns.barplot(x="2016", y="Country Code", data=total_bottom_ten_countries, palette="coolwarm")
plt.title("Bottom Ten Countries of Total Population (2016)",fontsize=10)
plt.xlabel("Total Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

#filter data for male population
male_population_data = df[df['Series Code']=='SP.POP.TOTL.MA.IN']

#sort data based on the male population for 2022
male_population_sorted =male_population_data.sort_values(by="2022",ascending=False)

#Get the top 10 countries with the highest male population for 2022
male_top_ten_countries = male_population_sorted .head(10)
print("Top ten countries of male population")
print(male_top_ten_countries[['Country Code']])

#filter data for male population
female_population_data = df[df['Series Code']=='SP.POP.TOTL.FE.IN']

#sort data based on the male population for 2022
female_population_sorted =female_population_data.sort_values(by="2022",ascending=False)

#Get the top 10 countries with the highest male population for 2022
female_top_ten_countries = female_population_sorted .head(10)
print("Top ten countries of female population")
print(female_top_ten_countries[['Country Code']])

# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,1)
sns.barplot(x="2022", y="Country Code", data=male_top_ten_countries, palette="viridis")
plt.title("Top ten conuntries of male population(2022)",fontsize=10)
plt.xlabel("Male Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

# Create the bar plot
plt.figure(figsize=(15, 6))
plt.subplot(2,2,2)
sns.barplot(x="2016", y="Country Code", data=female_top_ten_countries, palette="viridis")
plt.title("Top ten conuntries of female population(2022)",fontsize=10)
plt.xlabel("Female Population",fontsize=10)
plt.ylabel("Country",fontsize=10)
plt.show()

#merge male and female population data on 'Country Code'
merge_data=pd.merge(male_population_data,female_population_data,on="Country Code",suffixes=("_male","_female"))

#merged data
#calculate the total population for each country (male + female)
merge_data["Total population"] = merge_data["2022_male"] + merge_data ["2022_female"]

merge_data.head()

#sort data based on total population in descending order
sorted_data = merge_data.sort_values(by="Total population", ascending=False)

top_10_countries = sorted_data.head(10)

#create the staked bar plot
plt.figure(figsize=(12,6))
sns.barplot(x="Country Code",y="2022_female",data=top_10_countries,color="red",label="female Population")
sns.barplot(x="Country Code",y="2022_male",data=top_10_countries,bottom=top_10_countries["2022_female"],color="green",label="Male Population")
plt.xlabel("Country")
plt.ylabel("Population")
plt.legend()
plt.xticks(rotation=45,ha="right")
plt.show()

#select the top 10 countries with the highest total population
bottom_10_countries = sorted_data.tail(10)

# Create the stacked bar plot
plt.figure(figsize=(12, 6))
sns.barplot(x="Country Code", y="2022_female", data=bottom_10_countries, color="red", label="Female Population")
sns.barplot(x="Country Code", y="2022_male", data=bottom_10_countries, bottom=bottom_10_countries["2022_female"], color="green", label="Male Population")
plt.xlabel("Country")
plt.ylabel("Population")
plt.legend()
plt.xticks(rotation=45, ha="right")
plt.show()

